## 端口号
server:
  port: 8080

## Dubbo 服务消费者配置
dubbo:
  application:
    name: demo-consumer # 消息者名字
  registry:
#    address: zookeeper://127.0.0.1:2181 # 注册中心地址
    address: zookeeper://jasonzeng.top:2181?backup=jasonzeng.top:2182,jasonzeng.top:2183 # 注册中心地址
